### ISSUE TITLE
Add Enum support to DBConvert

### ISSUE THREAD

**Issue by nvivo** [nvivo/dbhelpers#10]

**Comment by zyz** [comment]
Dbhelpers is strong.But there is a problem, byte [] type errors.
I have modified the below a place.
Add else if.
case TypeCode.Object:
	if (type == typeof(Guid))
        	return ToGuidInternal(value, null);
	else if (type == typeof(byte[]))
		return value;
	break;

I wonder if you how to deal with this problem?

**Comment by nvivo** [comment]
Good call, I forgot this one. I just created a ticket (https://github.com/nvivo/dbhelpers/issues/12) and should release in the next version.

**Comment by nvivo** [comment]
Adding enum support has proven to be quite complicated. While it is possible, it requires too many checks to convert the value correctly, adding a lot of overhead. It also causes an extra check on the To(Type) which I'm not willing to add because of enums.

For now it is better to cast the value from an integer to the enum type.
