### ISSUE TITLE
How to use by execute store procedure 

### ISSUE THREAD

**Issue by chengn** [nvivo/dbhelpers#17]
i'm not find code about execute store procedure in readme.txt,can u write it?thank u.

**Comment by nvivo** [comment]
Hi. This is similar to pure ADO.NET. Just create a DbCommand,  set the CommandType property to StoredProcedure and execute it. 

Alternatively you can write the full statement as a regular query:

``` cs
var value = db.ExecuteScalar<int>("exec getSomeValueProc");
```

The exact syntax will vary depending on your database.
