### ISSUE TITLE
Does not work at all. Connection not initialized

### ISSUE THREAD

**Issue by SuheylZ** [nvivo/dbhelpers#19]
I tried using the DBHelper with the following:

 _sourceDB = new DBHelper("Source");

here is the connection string defined
    `<add name="Source" connectionString="data source=workstation;initial catalog=MCQ;integrated security=True;multipleactiveresultsets=True;" providerName="System.Data.SqlClient" />`

and it keeps giving error
 Connection not initialized

**Comment by nvivo** [comment]
Hi @MercedeX. This should work fine. Which version of the framework are you using?

Also, how are you using the helper? Which method are you calling?

**Comment by SuheylZ** [comment]
4.5.1
On May 4, 2016 3:11 PM, Natan Vivo notifications@github.com wrote:Hi @MercedeX. This should work fine. Which version of the framework are you using?

Also, how are you using the helper? Which method are you calling?

**Comment by nvivo** [comment]
I'll really need more context on this if you want some help.  The exact code you wrote and the stack trace if possible.

**Comment by nvivo** [comment]
Closing this due to lack of response. If you have more details, please reopen and I'd be glad to help.

**Comment by SuheylZ** [comment]
Can I use your library in my project [GenericDataManager](https://github.com/MercedeX/GenericDataManager)?
It is to provide the plain ADO.NET functionality by creating a custom IContextConsumer

**Comment by nvivo** [comment]
@MercedeX sure, go ahead.
