### ISSUE TITLE
Help to make an Insert with parameterized command

### ISSUE THREAD

**Issue by n00bDr01d** [nvivo/dbhelpers#21]
Please help a noob, I was trying to make a command

 var command = DbHelper.CreateCommand(@"INSERT INTO secApp(AppExe,AppDes) VALUES(@AppExe,@AppDes)");

then, I try to use an DbHelper.ExecuteNonQuery with erros,

Would you mind writing an example?

**Comment by nvivo** [comment]
DBHelper uses positional parameters. You should use this instead:

```
DbHelper.CreateCommand(@"INSERT INTO secApp(AppExe,AppDes) VALUES({0},{1})", appExe, appDes);
```
